POST {{keycloak-host}}/realms/{{keycloak-realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id={{keycloak-client-name}}&username={{demo-user}}&password={{demo-user-pw}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("Access token exists", function() {
        client.assert(response.body.hasOwnProperty("access_token"), "Response property 'access_token' does not exists");
    });

    client.global.set("access_token", response.body.access_token);
    client.log("Access token is " + response.body.access_token)
%}

###

GET {{java-service-host}}/secure/hello
Authorization: Bearer {{access_token}}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("Http /secure/hello returns 'Hello secure'", function() {
        client.assert(response.body === 'Hello secure', "Response body is not 'Hello secure'");
    });

    client.log("Response: " + response.body)
%}

###