version: '3'

services:
    keycloak:
        image: quay.io/keycloak/keycloak:25.0
        command:
            - start-dev
            - --import-realm
            - --health-enabled=true
        volumes:
            - ./imports/realm-export.json:/opt/keycloak/data/import/realm.json
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        ports:
            - "8085:8080"