version: '3'

volumes:
    postgres_data:
        driver: local

services:
    postgres:
        image: postgres:14.3
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: db-keycloak-user
            POSTGRES_PASSWORD: db-keycloak-pw
    keycloak:
        image: jboss/keycloak:16.1.1
        volumes:
            - ./imports:/opt/jboss/keycloak/imports
        environment:
            DB_VENDOR: POSTGRES
            DB_ADDR: postgres
            DB_DATABASE: keycloak
            DB_SCHEMA: public
            DB_USER: db-keycloak-user
            DB_PASSWORD: db-keycloak-pw
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
            KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json
        ports:
            - "8085:8080"
        depends_on:
            - postgres