version: '3'

volumes:
    postgres_data:
        driver: local

services:
    postgres:
        container_name: spring-boot-postgres_container
        image: postgres:15.3
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: development_db
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres_password}
        ports:
            - "5432:5432"