### This script creates a user 'larmic' and assigns client and realm test roles to user.

###
# @name Get admin user access token
POST {{host}}realms/master/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=admin-cli&username={{admin-name}}&password={{admin-password}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("Access token exists", function () {
        client.assert(response.body.hasOwnProperty("access_token"), "Response property 'access_token' does not exists");
    });

    client.global.set("access_token", response.body.access_token);
    client.log("Access token is " + response.body.access_token)
%}

###
# @name Add new user larmic (pw: test)
# NOTE: groups can not be automatically applied (even if the documentary says so)
#       see https://github.com/keycloak/keycloak/issues/13390
POST {{host}}admin/realms/{{realm}}/users
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "firstName": "{{add-user-first-name}}",
    "lastName": "{{add-user-last-name}}",
    "enabled": "true",
    "username": "{{add-user-name}}",
    "credentials": [
        {
            "type": "{{add-user-password}}",
            "value": "test",
            "temporary": false
        }
    ]
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 201, "Response status is not 200");
    });

    client.global.set("user_larmic_location", response.headers.valueOf("Location"));
    client.log(response.headers.valueOf("Location"))
%}

###
# @name Get larmic user id
GET {{user_larmic_location}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("id", function () {
        client.assert(response.body.hasOwnProperty("id"), "Response property 'id' does not exists");
    });

    client.global.set("user_larmic_id", response.body.id);
    client.log("User larmic id is " + response.body.id)
%}

###
# @name Get spring-boot-service-1 client id
GET {{host}}admin/realms/{{realm}}/clients?clientId={{client-name}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("id", function () {
        client.assert(response.body[0].hasOwnProperty("id"), "Response property 'id' does not exists");
    });

    client.global.set("client-id", response.body[0].id);
    client.log("Client id is " + response.body[0].id)
%}

###
# @name Get role id of realm role 'custom_realm_role'
GET {{host}}admin/realms/{{realm}}/roles/{{realm-role-name}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("id", function () {
        client.assert(response.body.hasOwnProperty("id"), "Response property 'id' does not exists");
    });

    client.global.set("realm-role-id", response.body.id);
    client.log("Custom realm role id is " + response.body.id)
%}

###
# @name Get role id of client role 'custom_client_role'
GET {{host}}admin/realms/{{realm}}/clients/{{client-id}}/roles/{{client-role-name}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("id", function () {
        client.assert(response.body.hasOwnProperty("id"), "Response property 'id' does not exists");
    });

    client.global.set("client-role-id", response.body.id);
    client.log("Custom client role id is " + response.body.id)
%}

###
# @name Add realm role to larmic
POST {{host}}admin/realms/{{realm}}/users/{{user_larmic_id}}/role-mappings/realm
Authorization: Bearer {{access_token}}
Content-Type: application/json

[{
    "id": "{{realm-role-id}}",
    "name": "{{realm-role-name}}"
}]


> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 204, "Response status is not 204");
    });
%}

###
# @name Add client role to larmic
POST {{host}}admin/realms/{{realm}}/users/{{user_larmic_id}}/role-mappings/clients/{{client-id}}
Authorization: Bearer {{access_token}}
Content-Type: application/json

[{
    "id": "{{client-role-id}}",
    "name": "{{client-role-name}}"
}]