name: spring-boot-keycloak

on:
    push:
        paths:
            - 'spring-boot-keycloak/**'
            - '.github/workflows/spring-boot-keycloak.yml'
    pull_request:
        paths:
            - 'spring-boot-keycloak/**'
            - '.github/workflows/spring-boot-keycloak.yml'

jobs:
    keycloak-service:
        name: Build spring boot using keycloak (service 1) with java version ${{ matrix.java }}
        runs-on: ubuntu-latest

        strategy:
            matrix:
                java: [ 17,18,19 ]

        steps:
            -   uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
            -   name: Setup java ${{ matrix.java }}
                uses: actions/setup-java@v3
                with:
                    distribution: 'temurin'
                    java-version: ${{ matrix.java }}
            -   run: mvn -B -f spring-boot-keycloak clean verify